[build]
  # 构建命令
  command = "npm run build"
  
  # 发布目录
  publish = ".next"
  
  # 构建环境变量
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# 重定向规则
[[redirects]]
  from = "/api/*"
  to = "https://core.flaretion.com/api/:splat"
  status = 200
  force = true

# 前端路由重定向 (SPA支持)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# 静态资源缓存
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 图片和字体缓存
[[headers]]
  for = "*.{jpg,jpeg,png,gif,webp,svg,ico,woff,woff2,ttf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 环境变量 (构建时)
[build.environment]
  NEXT_PUBLIC_API_URL = "https://core.flaretion.com"
  NEXT_PUBLIC_APP_NAME = "TaskMaster"
  NEXT_PUBLIC_ENV = "production"

# 部署设置
[build.processing]
  skip_processing = false

# 函数设置 (如果需要)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# 插件设置
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 开发设置
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  framework = "nextjs"
